files:
  - source: /src/XmlFormatterOsIndependent/Properties/Resources.resx
    translation: //src/XmlFormatterOsIndependent/Properties/%file_name%.%two_letters_code%.%file_extension%
  - source: src/XmlFormatterOsIndependent/Resources/*.md
    translation: /src/XmlFormatterOsIndependent/Resources/%file_name%.%two_letters_code%.%file_extension%
