//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlFormatterOsIndependent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Properties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Properties() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlFormatterOsIndependent.Properties.Properties", typeof(Properties).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlFormatterOsIndependent.Resources.AppDescription.md.
        /// </summary>
        public static string AboutWindow_Tab_General_Description_File {
            get {
                return ResourceManager.GetString("AboutWindow_Tab_General_Description_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlFormatterOsIndependent.Resources.ThirdPartyApps.json.
        /// </summary>
        public static string AboutWindow_Tab_General_ThirdPartyApps_File {
            get {
                return ResourceManager.GetString("AboutWindow_Tab_General_ThirdPartyApps_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinuxAvalonia.
        /// </summary>
        public static string Asset_LinuxFilter {
            get {
                return ResourceManager.GetString("Asset_LinuxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarwinAvalonia.
        /// </summary>
        public static string Asset_MacOsFilter {
            get {
                return ResourceManager.GetString("Asset_MacOsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsAvalonia.
        /// </summary>
        public static string Asset_WindowsFilter {
            get {
                return ResourceManager.GetString("Asset_WindowsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/XanatosX/XmlFormatter/discussions.
        /// </summary>
        public static string GitHub_Discuss {
            get {
                return ResourceManager.GetString("GitHub_Discuss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/XanatosX/XmlFormatter/issues.
        /// </summary>
        public static string GitHub_Issue {
            get {
                return ResourceManager.GetString("GitHub_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/XanatosX/XmlFormatter.
        /// </summary>
        public static string GitHub_Project {
            get {
                return ResourceManager.GetString("GitHub_Project", resourceCulture);
            }
        }
    }
}
