//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlFormatterOsIndependent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlFormatterOsIndependent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string AboutWindow_Tab_General {
            get {
                return ResourceManager.GetString("AboutWindow_Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discuss.
        /// </summary>
        public static string AboutWindow_Tab_General_Discuss {
            get {
                return ResourceManager.GetString("AboutWindow_Tab_General_Discuss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Help.
        /// </summary>
        public static string AboutWindow_Tab_General_GetHelp {
            get {
                return ResourceManager.GetString("AboutWindow_Tab_General_GetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party.
        /// </summary>
        public static string AboutWindow_Tab_ThirdParty {
            get {
                return ResourceManager.GetString("AboutWindow_Tab_ThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml Formatter.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask before closing.
        /// </summary>
        public static string ApplicationSettingsView_AskBeforeClosing {
            get {
                return ResourceManager.GetString("ApplicationSettingsView_AskBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled this does show a confirmation popup if you want to close the application.
        /// </summary>
        public static string ApplicationSettingsView_AskBeforeClosing_Tip {
            get {
                return ResourceManager.GetString("ApplicationSettingsView_AskBeforeClosing_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        public static string ApplicationSettingsView_CheckForUpdateOnStartup {
            get {
                return ResourceManager.GetString("ApplicationSettingsView_CheckForUpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does check if there is new version of the application available as soon as the application starts..
        /// </summary>
        public static string ApplicationSettingsView_CheckForUpdateOnStartup_Tip {
            get {
                return ResourceManager.GetString("ApplicationSettingsView_CheckForUpdateOnStartup_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme to display the application with.
        /// </summary>
        public static string ApplicationSettingsView_Theme_Tip {
            get {
                return ResourceManager.GetString("ApplicationSettingsView_Theme_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The updater used to download the update for the application..
        /// </summary>
        public static string ApplicationSettingsView_Updater_Tip {
            get {
                return ResourceManager.GetString("ApplicationSettingsView_Updater_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings.
        /// </summary>
        public static string BackupSettingsView_Export {
            get {
                return ResourceManager.GetString("BackupSettingsView_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export failed, because no file was selected or the settings could not be loaded.
        /// </summary>
        public static string BackupSettingsView_ExportFailed {
            get {
                return ResourceManager.GetString("BackupSettingsView_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting the settings was successful.
        /// </summary>
        public static string BackupSettingsView_ExportingSettingWasSuccessful {
            get {
                return ResourceManager.GetString("BackupSettingsView_ExportingSettingWasSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Settings.
        /// </summary>
        public static string BackupSettingsView_Import {
            get {
                return ResourceManager.GetString("BackupSettingsView_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load setting for import, please check the selected file.
        /// </summary>
        public static string BackupSettingsView_ImportedSettingNotLoaded {
            get {
                return ResourceManager.GetString("BackupSettingsView_ImportedSettingNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing the setting was successful.
        /// </summary>
        public static string BackupSettingsView_ImportingSettingWasSuccessful {
            get {
                return ResourceManager.GetString("BackupSettingsView_ImportingSettingWasSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string MainWindow_Load {
            get {
                return ResourceManager.GetString("MainWindow_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_Menu_About {
            get {
                return ResourceManager.GetString("MainWindow_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainWindow_Menu_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_Menu_File {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainWindow_Menu_Help {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_Menu_OpenSettings {
            get {
                return ResourceManager.GetString("MainWindow_Menu_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string MainWindow_Menu_Plugins {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issue.
        /// </summary>
        public static string MainWindow_Menu_ReportIssue {
            get {
                return ResourceManager.GetString("MainWindow_Menu_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        public static string MainWindow_Menu_Update {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainWindow_Save {
            get {
                return ResourceManager.GetString("MainWindow_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file path for formatting.
        /// </summary>
        public static string MainWindow_SelectFilePath {
            get {
                return ResourceManager.GetString("MainWindow_SelectFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}.
        /// </summary>
        public static string MainWindow_Status_Template {
            get {
                return ResourceManager.GetString("MainWindow_Status_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        public static string Mode_Flat {
            get {
                return ResourceManager.GetString("Mode_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted.
        /// </summary>
        public static string Mode_Formatted {
            get {
                return ResourceManager.GetString("Mode_Formatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string PluginInformationView_Author_Colon {
            get {
                return ResourceManager.GetString("PluginInformationView_Author_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PluginInformationView_Description {
            get {
                return ResourceManager.GetString("PluginInformationView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string PluginInformationView_Name_Colon {
            get {
                return ResourceManager.GetString("PluginInformationView_Name_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string PluginInformationView_Version_Colon {
            get {
                return ResourceManager.GetString("PluginInformationView_Version_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Manager.
        /// </summary>
        public static string PluginManagerWindow_Title {
            get {
                return ResourceManager.GetString("PluginManagerWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SettingsWindow_Close {
            get {
                return ResourceManager.GetString("SettingsWindow_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        public static string SettingsWindow_SaveAndClose {
            get {
                return ResourceManager.GetString("SettingsWindow_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string SettingsWindow_Tab_Application {
            get {
                return ResourceManager.GetString("SettingsWindow_Tab_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string SettingsWindow_Tab_Backup {
            get {
                return ResourceManager.GetString("SettingsWindow_Tab_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotfolder.
        /// </summary>
        public static string SettingsWindow_Tab_Hotfolder {
            get {
                return ResourceManager.GetString("SettingsWindow_Tab_Hotfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string SettingsWindow_Tab_Logging {
            get {
                return ResourceManager.GetString("SettingsWindow_Tab_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
    }
}
