name: Check pull request

on: [pull_request]

jobs:
   checkAvaloniaBuild:
     name: Check Avalonia build
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
         with:
            lfs: true
       - name: Restore
         run: dotnet restore
         shell: powershell
       - name: Build project
         run: dotnet publish .\src\XmlFormatterOsIndependent\ -c Release -r win-x64 --self-contained true
         shell: powershell
