name: Check pull request

on: [pull_request]

jobs:
   checkWinFormsBuild:
     name: Check windows forms build
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Install nuget
         uses: nuget/setup-nuget@v1
       - name: Nuget restore
         run: nuget restore
         shell: powershell
       - name: Setup msbuild
         uses: microsoft/setup-msbuild@v1.0.2
       - name: switch folder
         run: cd src\XmlFormatter
         shell: powershell
       - name: Build project
         run: msbuild /t:Build /p:Configuration=Release
         shell: powershell
   checkAvaloniaBuild:
     name: Check Avalonia build
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
       - name: Install nuget
         uses: nuget/setup-nuget@v1
       - name: Nuget restore
         run: nuget restore
         shell: powershell
       - name: switch folder
         run: cd src\XmlFormatterOsIndependent
         shell: powershell
       - name: Build project
         run: dotnet publish -c Release -r win-x64 --self-contained true
         shell: powershell