name: Live build

on: [push]
  #push:
  #  tags:
  #   - '*'

jobs:
   build:
     name: Create build artifact
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
         with: 
           ref: develop
       - name: Get current tag
         run: echo ::set-env name=tag::(("${env:GITHUB_REF}" -split "/")[-1] -replace " ","")
       - name: Show current tag
         run: echo "${env:GITHUB_REF}"
       - name: Install nuget
         uses: nuget/setup-nuget@v1
       - name: Setup msbuild
         uses: microsoft/setup-msbuild@v1.0.0
       - name: Build project
         run: |
           nuget restore
           msbuild /t:Build /p:Configuration=Release
         shell: powershell
       - name: Create artifacts
         run: |
           $tags = "${env:GITHUB_REF}" -split "/"
           $tag = $tags[-1]
           $tag = $tag -replace " ",""
           echo $tag
           $xmlFormatter = -join($tag, "_XmlFormatter.zip")
           $jsonPlugin = -join($tag, "_JsonPlugin.zip")
           mkdir ..\Artifacts
           mkdir ..\Artifacts\XmlFormatter\
           mkdir ..\Artifacts\JsonPlugin\
           mv .\XmlFormatter\bin\Release\** ..\Artifacts\XmlFormatter\
           cd ..\Artifacts\
           mv .\XmlFormatter\Plugins\*Json*.dll .\JsonPlugin\
           7z a $xmlFormatter .\XmlFormatter\**
           7z a $jsonPlugin .\JsonPlugin\**
         shell: powershell
       - name: Create Release
         id: create_release
         uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ github.ref }}
           release_name: Release ${{ github.ref }}
           body: Body goes here!
           draft: true
           prerelease: false
       #- name: Create GitHub release
         #uses: Roang-zero1/github-upload-release-artifacts-action@master
         #with:
          #args:
          #  - ..\Artifacts\*.zip
          #env:
          #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       #- name: Upload XmlFormatter artifacts
       #  uses: actions/upload-artifact@v1
       #  with:
       #    name: ${{ env.GITHUB_REF##*/ }}_XmlFormatter
       #    path: ..\Artifacts\XmlFormatter\
       #- name: Upload JsonPlugin artifacts
       #  uses: actions/upload-artifact@v1
       #  with:
       #    name: ${{ env.GITHUB_REF##*/ }}_JsonPlugin
       #    path: ..\Artifacts\JsonPlugin\
       #- name: Create Release
