name: Create last unstable build artifact

on: [push]
  #push:
    #branches:
      #- develop

jobs:
   build:
     name: Create build artifact
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
         with: 
           ref: develop
       - name: Nuget restore
         run: nuget restore
         shell: powershell 
          