name: Latest unstable build artifact

on:
  pull_request:
    types: [closed] 

jobs:
   build:
     if: github.event.pull_request.merged == true
     name: Create build artifact
     runs-on: windows-latest
     steps:
       - name: Clone repository
         uses: actions/checkout@v2
         with: 
           ref: develop
       - name: Install nuget
         uses: nuget/setup-nuget@v1
       - name: Setup msbuild
         uses: microsoft/setup-msbuild@v1.0.0
       - name: Build project
         run: |
           nuget restore
           msbuild /t:Build /p:Configuration=Release
         shell: powershell
       - name: Create artifacts
         run: |
           mkdir ..\Artifacts
           mkdir ..\Artifacts\XmlFormatter\
           mkdir ..\Artifacts\JsonPlugin\
           mv .\XmlFormatter\bin\Release\** ..\Artifacts\XmlFormatter\
           cd ..\Artifacts\
           mv .\XmlFormatter\Plugins\*Json*.dll .\JsonPlugin\
         shell: powershell
       - name: Upload XmlFormatter artifacts
         uses: actions/upload-artifact@v1
         with:
           name: LatestDevelopment_XmlFormatter
           path: ..\Artifacts\XmlFormatter\
       - name: Upload JsonPlugin artifacts
         uses: actions/upload-artifact@v1
         with:
           name: LatestDevelopment_JsonPlugin
           path: ..\Artifacts\JsonPlugin\
